travis:
  secure:
    BINSTAR_TOKEN: p74W8vuDLQLMyN1JtzV84tL7bzdbdIbYiv34fTXGIe8jThUNjNWTZ1nJyd/900NOHR6PEb511mJJvzmKR/k+IXBa2XkPGS933Luxghn2rKv+EF+NgL0sHe84l9Axo9af0Y0q+H5eBCQk2zULgxX8HRkYtFlCg3mk8UqMaLVPqSgdQPTDR2zTFya5EhAd1r0UPCMTQvuvU37FxGXQMPwX/kUClF7l3vnZWCErij8mPmoZoamcplfyejASLh96ygxaxFUg+PaHTZ7aSUtf0lho6WohWves927GEerrSDg1CW9CIrY43bLA/Okp/jb8KbCwOTPupjuqe3msCvoewHgNPtii5vqc/Ijofz/E0r4ty9aSQ3x2cBr+eOKcWpEWWShTsnJwea5ldqip5T4LsoIleOtZdvnURkdK/SNBNan5JXT2FuPH7pXKBn2cwfRXaovZlfZqwGRb4ajjcoiFh8khaFYqzi5qNNpWzdKcdm2Jwb2mvzIHda77QwCNQiVEQSsUmqUwsmygh2T9v8KW6rRZwayQRp3/pU+Vshs9P8cQpQVuhzcn3PD+T5g2g5SnpD11XAU3kcTGeAqzmIckZjicf+lYOj1BntT/Yt6Rv3rXKwxQCrWDQ0gCVqxsT9XBZI1LLTlEzCEb9yXUQMRwa8y3+W9OB+qPqJYxAf8RiCehtVE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
