travis:
  secure:
    BINSTAR_TOKEN: e6kq7ur3fcD9i32KgFWPhBOLyvzmycA3zEEdIcLdh3nFpq4UqJLIvZTM4OnMhTguA6N0Q7Pqr/7cUzrLv8+mBOUhg2SqHDuy1K6S126R/4bcHrHRBLBpvRr/nz+ITv+7IFhV67em6U5fh3RsE13YI2iXBSdF6y+0J+wj51SbMVsc5Y9AFOauktXXqc4Sd20jzcytSeIfkz59luP+/oz6BtWG+hlmufoAvC4SxYa9rUhTMG3dPcpbFRrzS38KdRcKOOxxTMh1HcmfP43pvML0vW3hq0fL9bVOY+kCrYdoobcwND55t0O0Ad5cTILGPOkn/vnh5N3r9di8JwiQkuBa3B5CMENOMt1YDO2paOU3saGyTPmtguuCTdEmZp49VG/A8PYxYzneoiGrTA9eZcJwfNnTFfoZXPLSKXLU0LLVz8daK9mjTurIy4zkZ2dGYYNGvgDcVo2i1kbOwTnMp4BSIPdGF2hTXa6jRfu2tokpO/csJ8XAK2RPPH8octze0RiC42YGU5Xz7iNkJRFOekrqhfisfz3Bqa7TFydkAXpUkbUJDoJoHQRyw7RuNbP0wwsAP7uODrzXKDQpEsrf5G1UTtOqTW0xifkNF7Fvw+TKt6ycND4ThMK6hf5eQVFkT1RWohnsh5QPdabvGmSnX45+2J+N3wSqsZd3IghqS47AVvw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
